version: '3.8'
services:
  yii2-app:
    image: mdsahiloss/yii2-app-basic:1.0  # or use a specific tag like :abc1234
    ports:
      - "8080:80"
    restart: always
    environment:
      - APP_ENV=production
volumes:
  db_data: