---
- name: Deploy Yii2 app as a Swarm service
  hosts: all
  become: true
  tasks:
    # - name: Deploy the stack
    #   shell: $([ ! -d "/opt/yii-app-basic/" ] && sudo mkdir -p "/opt/yii-app-basic/")
    - name: Create a Docker stack file
      copy:
        dest: /opt/yii-app-basic/docker-compose.yml
        content: |
          version: '3.8'
          services:
            yii2-app:
              image: mdsahiloss/yii2-app-basic:1.0  # or use a specific tag like :abc1234
              ports:
                - "8080:80"
              restart: always
              environment:
                - APP_ENV=production
          volumes:
            db_data:

    - name: Deploy the stack
      shell: docker stack deploy -c /opt/yii-app-basic/docker-compose.yml yii2app
