name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

env:
  IMAGE_NAME: mdsahiloss/yii2-app-basic
  IMAGE_TAG: ${{ github.sha }}
  SERVICE_NAME: yii2app_yii2-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image
        run: docker push $IMAGE_NAME:$IMAGE_TAG

      - name: SSH and update Swarm service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            script: |
            sudo docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            sudo docker service update \
              --image ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
              --with-registry-auth \
              --force \
              ${{ env.SERVICE_NAME }}
